env:
  browser: true
  es2020: true
extends:
  - google
  - prettier
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typeform/eslint-config
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - no-loops
  - '@typescript-eslint'
globals: {
  process: true,
  __dirname: true
}
rules: {
  no-console: 2,
  no-loops/no-loops: 2,
  no-unused-vars: 'off',
  '@typescript-eslint/no-unused-vars': [
    'error',
    {
      argsIgnorePattern: '^_'
    }
  ],
  no-mixed-spaces-and-tabs: [
    'error',
    'smart-tabs'
  ],
  indent: [
    'error',
    2
  ],
  linebreak-style: [
      'error',
      'unix'
  ],
  quotes: [
      'error',
      'single'
  ],
  semi: [
      'error',
      'always'
  ]
}
