env:
  browser: true
  es2020: true
extends:
  - google
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'no-loops'
globals: {
  process: true,
  __dirname: true
}
rules: {
  no-console: 2,
  no-loops/no-loops: 2,
  # @ToDo fix the below rule issue and remove it
  '@typescript-eslint/ban-types': 'off',
  # @ToDo fix the below rule issue and remove it
  '@typescript-eslint/no-explicit-any': 'off',
  no-mixed-spaces-and-tabs: [
    'error',
    'smart-tabs'
  ],
  indent: [
    'error',
    2
  ],
  linebreak-style: [
      'error',
      'unix'
  ],
  quotes: [
      'error',
      'single'
  ],
  semi: [
      'error',
      'always'
  ]
}
